"""set defaut  distance for jogging

Revision ID: 3b914a868d64
Revises: ea80cb5b3f8c
Create Date: 2025-08-10 13:56:31.857682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b914a868d64'
down_revision: Union[str, Sequence[str], None] = 'ea80cb5b3f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
