"""set date and time

Revision ID: 5ae18ff0c023
Revises: 700b8a0346a2
Create Date: 2025-08-12 21:25:02.591206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ae18ff0c023'
down_revision: Union[str, Sequence[str], None] = '700b8a0346a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogging', sa.Column('date_start', sa.Date(), nullable=True))
    op.alter_column('jogging', 'time_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jogging', 'time_start',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('jogging', 'date_start')
    # ### end Alembic commands ###
