"""set new column in table - likes

Revision ID: 659339d2ede7
Revises: b57ab281fc42
Create Date: 2025-08-15 11:30:03.424554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659339d2ede7'
down_revision: Union[str, Sequence[str], None] = 'b57ab281fc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_jogging', sa.Column('like', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_jogging', 'like')
    # ### end Alembic commands ###
