"""rename column with jogging2

Revision ID: 700b8a0346a2
Revises: 81c45a5317d2
Create Date: 2025-08-12 16:43:58.490639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700b8a0346a2'
down_revision: Union[str, Sequence[str], None] = '81c45a5317d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogging', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('jogging', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogging', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('jogging', 'description')
    # ### end Alembic commands ###
