"""rename column with jogging

Revision ID: 81c45a5317d2
Revises: 6db862e3df10
Create Date: 2025-08-12 13:26:45.242374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c45a5317d2'
down_revision: Union[str, Sequence[str], None] = '6db862e3df10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogging', sa.Column('discription', sa.String(), nullable=False))
    op.drop_column('jogging', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogging', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('jogging', 'discription')
    # ### end Alembic commands ###
