"""set new table - otheruserjogging

Revision ID: b57ab281fc42
Revises: 5ae18ff0c023
Create Date: 2025-08-15 11:11:13.404065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57ab281fc42'
down_revision: Union[str, Sequence[str], None] = '5ae18ff0c023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_jogging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogging_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogging_id'], ['jogging.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_jogging')
    # ### end Alembic commands ###
