"""add start_coord column

Revision ID: ea80cb5b3f8c
Revises: 5add40a80667
Create Date: 2025-08-05 12:16:44.427417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea80cb5b3f8c'
down_revision: Union[str, Sequence[str], None] = '5add40a80667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('start_coord', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'start_coord')
    # ### end Alembic commands ###
